// Auto-generated TypeScript definitions from Apex classes
// Generated by apex-ts

export interface Contact {
  firstName: string;
  lastName: string;
  phone: string;
  birthDate: string;
  addresses: Address[];
}

declare module '@salesforce/apex/Contact.createContact' {
  export default function createContact(params: {
    firstName: string;
    lastName: string;
  }): Promise<Contact>;
}


export interface Account {
  name: string;
  email: string;
  age: number;
  isActive: boolean;
  tags: string[];
  scores: Record<string, number>;
}

declare module '@salesforce/apex/Account.getAccountById' {
  export default function getAccountById(params: {
    accountId: string;
  }): Promise<Account>;
}
declare module '@salesforce/apex/Account.searchAccounts' {
  export default function searchAccounts(params: {
    query: string;
    maxResults: number;
  }): Promise<Account[]>;
}
declare module '@salesforce/apex/Account.updateEmail' {
  export default function updateEmail(params: {
    newEmail: string;
  }): Promise<void>;
}


export interface Order {
  orderId: string;
  accountId: string;
  orderDate: string;
  totalAmount: number;
  status: string;
  items: Product[];
}

declare module '@salesforce/apex/Order.getOrderById' {
  export default function getOrderById(params: {
    orderId: string;
  }): Promise<Order>;
}
declare module '@salesforce/apex/Order.getOrdersByAccount' {
  export default function getOrdersByAccount(params: {
    accountId: string;
    maxRecords: number;
  }): Promise<Order[]>;
}
declare module '@salesforce/apex/Order.createOrder' {
  export default function createOrder(params: {
    accountId: string;
    totalAmount: number;
    items: Product[];
  }): Promise<Order>;
}
declare module '@salesforce/apex/Order.updateOrderStatus' {
  export default function updateOrderStatus(params: {
    orderId: string;
    newStatus: string;
  }): Promise<void>;
}


export interface Product {
  id: string;
  name: string;
  price: number;
  description: string;
  isAvailable: boolean;
  categories: string[];
  attributes: Record<string, string>;
}

declare module '@salesforce/apex/AccountController.getAccounts' {
  export default function getAccounts(params: {
    maxRecords: number;
  }): Promise<Account[]>;
}
declare module '@salesforce/apex/AccountController.createAccount' {
  export default function createAccount(params: {
    name: string;
    email: string;
    phone: string;
  }): Promise<Account>;
}
declare module '@salesforce/apex/AccountController.deleteAccount' {
  export default function deleteAccount(params: {
    accountId: string;
  }): Promise<void>;
}
declare module '@salesforce/apex/AccountController.getAccountWithContacts' {
  export default function getAccountWithContacts(params: {
    accountId: string;
  }): Promise<Account>;
}


declare module '@salesforce/apex/AccountService.getAccountStatistics' {
  export default function getAccountStatistics(): Promise<Record<string, number>>;
}
declare module '@salesforce/apex/AccountService.searchAccountsByIndustry' {
  export default function searchAccountsByIndustry(params: {
    industry: string;
    maxResults: number;
  }): Promise<Account[]>;
}
declare module '@salesforce/apex/AccountService.validateAccount' {
  export default function validateAccount(params: {
    accountId: string;
  }): Promise<boolean>;
}


